name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour at the start of the hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          ref: master # Adjust this to your default branch

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/TRaSH-Guides/Guides.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main

      - name: Push Changes
        run: |
          git push origin main
